name: Build and upload assets

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc: ['8.10.7']

    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.6.2.0

      - uses: actions/cache@v3
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: release-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project') }}
          restore-keys:
            release-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project') }}
            release-${{ runner.os }}-${{ matrix.ghc }}-

      - name: Update cabal index state
        run: cabal update

      - name: Configure
        if: matrix.os == 'ubuntu-latest'
        run: |
          cabal configure \
            --ghc-options="-split-sections" \
            --enable-executable-static \
            ;

      - name: Build single binary
        run: |
          cabal install \
            -O2 \
            --overwrite-policy=always \
            --install-method=copy \
            --installdir=. \
            ;

      - name: Compress assets
        run: tar -czf haskellorls.tar.gz haskellorls

      - name: Upload assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: haskellorls.tar.gz
          asset_name: haskellorls-${{ matrix.os }}.tar.gz
          asset_content_type: application/gzip
