name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc: ['8.10.4', '8.8.4', '8.6.5']

    steps:
      - uses: haskell/actions/setup@v1
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.2.0.0

      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project') }}
            ${{ runner.os }}-${{ matrix.ghc }}-

      - name: Update cabal index state
        run: cabal update

      - name: Add path
        run: echo "$HOME/.cabal/bin" >> $GITHUB_PATH

      - name: Install goldplate
        run: cabal install --overwrite-policy=always goldplate

      - uses: actions/checkout@v2

      - name: Build
        run: cabal install --overwrite-policy=always

      - name: Run tests
        run: goldplate goldplate --pretty-diff
