name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc: ['9.2.2', '9.0.2', '8.10.7', '8.8.4', '8.6.5']

    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.6.2.0

      - uses: actions/cache@v3
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ci-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project') }}
          restore-keys: |
            ci-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project') }}
            ci-${{ runner.os }}-${{ matrix.ghc }}-

      - name: Add path
        run: |
          mkdir -p ~/bin
          echo ~/bin >> "$GITHUB_PATH"
          echo ~/.cabal/bin >> "$GITHUB_PATH"

      - name: Install goldplate
        run: |
          case "$OSTYPE" in
            linux* )
              curl -L https://github.com/fugue/goldplate/releases/download/v0.2.1/goldplate-v0.2.1-linux-x86_64.tar.gz | tar xz -C ~/bin
              ;;
            darwin* )
              curl -L https://github.com/fugue/goldplate/releases/download/v0.2.1/goldplate-v0.2.1-darwin-x86_64.tar.gz | tar xz -C ~/bin
              ;;
          esac

      - name: Build
        run: cabal install --overwrite-policy=always -j

      - name: Run tests
        run: goldplate golden-test --pretty-diff

  cabal-format:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ghc: ['8.10.7']

    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.6.2.0

      - uses: actions/cache@v3
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: format-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project') }}
          restore-keys: |
            format-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project') }}
            format-${{ runner.os }}-${{ matrix.ghc }}-

      - name: Add path
        run: echo ~/.cabal/bin >> "$GITHUB_PATH"

      - name: Install cabal-fmt
        run: cabal install --overwrite-policy=always -j cabal-fmt

      - name: Run cabal-fmt
        run: cabal-fmt --check --Werror haskellorls.cabal

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run ormolu
        uses: mrkkrp/ormolu-action@v5

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/hlint-setup@v2
        with:
          version: '3.4'

      - name: Run hlint
        uses: haskell/actions/hlint-run@v2
        with:
          fail-on: status
          path: '["app/", "src/"]'

  actionlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
