name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc: ['9.0.1', '8.10.7', '8.8.4', '8.6.5']

    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.4.0.0

      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ci-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project') }}
          restore-keys: |
            ci-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project') }}
            ci-${{ runner.os }}-${{ matrix.ghc }}-

      - name: Update cabal index state
        run: cabal update

      - name: Add path
        run: echo ~/.cabal/bin >> "$GITHUB_PATH"

      - name: Install goldplate
        run: cabal install --overwrite-policy=always goldplate

      - name: Build
        run: cabal install --overwrite-policy=always

      - name: Run tests
        run: goldplate golden-test --pretty-diff
