name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc: ['8.10.3', '8.8.4']

    steps:
      - uses: haskell/actions/setup@v1
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.2.0.0

      - name: Update cabal index state
        run: cabal update

      - name: Add path
        run: echo "$HOME/.cabal/bin" >> $GITHUB_PATH

      - name: Install goldplate
        run: cabal install --overwrite-policy=always goldplate

      - uses: actions/checkout@v2

      - name: Build
        run: cabal install --overwrite-policy=always --installdir=bin

      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
            ${{ runner.os }}-${{ matrix.ghc }}-

        # NOTE: Always failure to run test on macOS if run it on project root.
        # So need to change working directory to `golden-test` to pass test.
        # But on Linux, can pass tests on both working directories. This is
        # work arround.
      - name: Run tests
        run: goldplate . --pretty-diff
        working-directory: ./golden-test
