name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc: ['8.10.3', '8.8.4']

    steps:
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.2.0.0

      - name: Add path
        run: echo "$HOME/.cabal/bin" >> $GITHUB_PATH

      - name: Install goldplate
        run: cabal install --overwrite-policy=always goldplate

      - uses: actions/checkout@v2

      - name: Build
        run: cabal install --overwrite-policy=always --installdir=bin

      - name: Run tests
        run: goldplate golden-test --pretty-diff
