name: Release and upload assets

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc: ['9.2.5']
        cabal: ['3.6.2.0']

    steps:
      - uses: actions/checkout@v3

      - id: setup-haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Freeze dependencies
        run: cabal freeze

      - uses: actions/cache@v3
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: release-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys:
            release-${{ runner.os }}-${{ matrix.ghc }}-

      - name: Build single binary
        run: |
          rm cabal.project.freeze
          cabal install \
            --jobs \
            --install-method=copy \
            --installdir=. \
            --enable-optimization=2 \
            --enable-split-sections \
            ;

      - name: Compress assets
        run: |
          set -eu

          mkdir assets
          readonly version='${{ github.ref_name }}'
          case "$OSTYPE" in
            linux-gnu )
              readonly os=linux
              ;;
            darwin* )
              readonly os=macos
              ;;
          esac
          arch=$(uname -m)
          readonly arch

          tar -czf "assets/haskellorls-$version-$os-$arch.tar.gz" haskellorls

      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: assets/*
